const assert = require('node:assert/strict');
const { readFile } = require('node:fs/promises');
const path = require('node:path');
const test = require('node:test');

const root = path.resolve(__dirname, '..');

test('browser UI exposes team task and trace surfaces', async () => {
  const html = await readFile(path.join(root, 'public', 'index.html'), 'utf8');
  const app = await readFile(path.join(root, 'public', 'app.js'), 'utf8');
  const css = await readFile(path.join(root, 'public', 'style.css'), 'utf8');

  assert.match(html, /class="workspace[^"]*command-workspace|class="command-workspace[^"]*workspace/);
  assert.match(html, /aria-label="Main terminal and agent workspace"/);
  assert.match(html, /id="main-terminal-region"/);
  assert.match(html, /aria-label="Main command terminal"/);
  assert.match(html, /id="agent-workspace"/);
  assert.match(html, /aria-label="Agent card workspace"/);
  assert.match(html, /id="agent-cards"/);
  assert.match(html, /id="show-removed-agents"/);
  assert.match(html, /id="team-tasks"/);
  assert.match(html, /id="team-flow"/);
  assert.match(html, /id="team-trace"/);
  assert.match(html, /id="team-inbox"/);
  assert.match(html, /id="team-message"/);
  assert.match(html, /id="send-team-message"/);
  assert.match(html, /class="team-review"/);
  assert.match(html, /<summary>Review/);
  assert.match(html, /<details class="team-review"[\s\S]*id="team-roster"[\s\S]*id="team-flow"[\s\S]*id="team-messages"[\s\S]*<\/details>/);
  assert.doesNotMatch(html, /<details class="team-review"[^>]*open/);
  assert.match(app, /data-agent-id/);
  assert.match(app, /renderAgentCard/);
  assert.match(app, /renderAgentCards/);
  assert.match(app, /agent-card-reply/);
  assert.match(app, /agent-card-message/);
  assert.match(app, /sendAgentMessage/);
  assert.match(app, /sendTeamMessage/);
  assert.match(app, /\/api\/team\/messages/);
  assert.match(app, /data-agent-message/);
  assert.match(app, /data-agent-send/);
  assert.match(app, /agent-card-raw/);
  assert.match(app, /removeTeamAgent/);
  assert.match(app, /renderAgentTaskActions/);
  assert.match(app, /agent-card-task-actions/);
  assert.match(app, /cardActionContext/);
  assert.match(app, /taskTargetsAgent/);
  assert.match(app, /task\.assignedTo === '@leader'/);
  assert.doesNotMatch(app, /task\.mentions[\s\S]{0,120}\.includes\(`@\$\{agentId\}`\)/);
  assert.match(app, /shareterminal\.showRemovedAgents/);
  assert.match(app, /renderRemovedAgentCard/);
  assert.match(app, /renderTeamFlow/);
  assert.match(app, /renderTeamFlowNode/);
  assert.match(app, /team-flow-worker/);
  assert.match(app, /handleMainTerminalMention/);
  assert.match(app, /\/api\/team\/commands\/mention/);
  assert.match(app, /mainInputBuffer/);
  assert.match(app, /mainMentionCommand/);
  assert.match(app, /safeLocalStorage/);
  assert.match(app, /team-task-result/);
  assert.match(app, /\/api\/team\/tasks\/\$\{encodeURIComponent\(task\.taskId\)\}\/dispatch/);
  assert.match(app, /\/api\/team\/tasks\/\$\{encodeURIComponent\(task\.taskId\)\}\/cancel/);
  assert.match(app, /\/api\/team\/tasks\/\$\{encodeURIComponent\(task\.taskId\)\}\/retry/);
  assert.match(app, /\/api\/team\/tasks\/\$\{encodeURIComponent\(task\.taskId\)\}\/resume/);
  assert.match(app, /\/api\/team\/inbox\/\$\{encodeURIComponent\(item\.inboxId\)\}\/ack/);
  assert.match(app, /loadTeamTrace\(item\.inboxId\)/);
  assert.match(app, /\/api\/team\/inbox/);
  assert.match(app, /\/api\/team\/trace\//);
  assert.match(app, /team-agent-workspace/);
  assert.match(app, /agent\.workspace/);
  assert.match(css, /\.main-terminal-region/);
  assert.match(css, /\.agent-workspace/);
  assert.match(css, /\.agent-card/);
  assert.match(css, /\.agent-card-task-actions/);
  assert.match(css, /\.agent-card-message/);
  assert.match(css, /\.agent-card-message-input/);
  assert.match(css, /\.team-review/);
  assert.match(css, /\.team-message-composer/);
  assert.match(css, /\.agent-card-reply/);
  assert.match(css, /\.agent-card-raw/);
  assert.match(css, /\.team-flow/);
  assert.match(css, /\.team-flow-node/);
});
